//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int IdReserva { get; set; }
        public Nullable<int> IdPelicula { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdSala { get; set; }
        public Nullable<int> IdHorario { get; set; }
        public Nullable<int> IdFuncion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Funcion Funcion { get; set; }
        public virtual Horario Horario { get; set; }
        public virtual Pelicula Pelicula { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
